language: ruby
deploy:
  provider: heroku
  api_key:
    secure: lVNTTHTnXmCDxAEWo4ysS0aFZIM0leBLWrSKPiMfu0Mo0yXoSBk+bwNzi7ob/fZG4lqL4TMCrWkXF4e2UoTvx7xH96VbnULtRIOGi5oRCQ+RS+oSUFg8UanKxRJFQtNnVonnSsR1Vls+h6TbAa36rWRkWK03OKiLgAMyDbQunZ79LVdBXUQm+M2PmLRxVvWn7e5rY3XVgSAoAKx+/lRrbXTHxrvEgL8G2920GquS7qtHB/A1EGehrojMuMMfKP4tWCkNh252hSSSKl2g+2zXBVfjNw/76tMvJLoe2wYH4TAxaztelhD6RiO+LbFy9stQP0rPoF8Haun3mU1Y8Ny+cdtR+EEb39cYOGaO2ImMn9QrhjnYrkXOko9ARE5ok6EG1u1RumARqCv9MaIvUr4kuPbOgcbmmm1UZ2Z2y0rNnRXbZkjOcUt/ZdWVH1rqJ6awEj9vAbzwmxz3jDlcmYILft9iQ5ETU2A3nN3sqEQmveifm0OtJerWLwdA2D9iFYsu83Ipa5t3ZIfwqDCvSyOYtNKjMHInbFZIR0tx1xOagSGmKZ+QghUIUMFhMoBwTf4C/x4/Z+ufQOZe/zkIISjCUxOC+pXpiwBgNXP9cDbci5hHQad8ypPt8x6rgXk15RKsUYn3nmMvs5CgLgaMgUYlIndtSYM8GoMEK/hxeqNnl7Q=
  app: news-checker-search
  run:
    - 'rake db:migrate'
    - 'rake db:seed'
    - 'rake cleanup'
