language: ruby
deploy:
  provider: heroku
  api_key:
    secure: iy5tgTo+i91GH2SLUm9UbYdTMbx63OU1hHzX56eFmoC974HcHBT9RMu7PQLEVIAvmnS7rdU48fFrDDdR1TEmxdVagcpTVD9E53mdrZQyxQEAGQBa87K9oiE9ENJwpFJV01jmuJfb0mXiwVWOcQATO/lAt+Fa9DvaX7RhHLJCMn2p0uz3E4Nvm4n2XIPGxqAJvk2zovTgUqqMoMarNMY8Emsn7nR0SAmshhreszVQ6tbKaPd26TDm+T/emNmseUST6FAv2+74somGSZEYsqBdO5smnuuxEYp7XSyraxCGdakf8ZXQUFZQ8lOGtf1FrZNZ5Wn9RTmanWyThPwzU/DCs+vQKYp4rGQGUHVIuTzNmBFPJY3EJ3tMthLw2MPb7c1UnpHY/iFhsk/NWuz7m57i+UKZaiqNPgCq1RpcmRvxNJPOMVqfVJt3K7yJsc1cg8ZttvYhx1kaym/QOTjAyvCgLKSiXLoePIBuDMZeFWrAz7MPJZFe9RITXDYQ+RcaN/DACa3pD3kV5T97aeRve2NHLYY8pIeezMh9bwI+86LKAGplA+ZM76xpx6/u5ywYGPsrf9INZVe9+uZ76zQUB4mXk6eLUcbZuH/tu8tz5pXyeVYfq/C52YHfBeDCaAwP9j5rKY6DRhNqhI+iugavCfUlGYRoIFcj0DAsZWTwpIkxSKg=
  app: news-checker-search
  run:
    - 'rake db:migrate'
    - 'rake db:seed'
    - 'rake cleanup'
